title: 'Itsallcode Blog'
baseURL: 'http://blog.itsallcode.org/'
languageCode: 'en-us'
defaultContentLanguage: 'en'
pygmentsCodeFences: true
theme: 'anubis2'
pagination:
  pagerSize: 5
author:
  name: 'Itsallcode.org authors'




params:
  description: 'Home of the everything-is-code enthusiasts'
  mainSections: ['posts']
  anubis2:
    colortheme: 'auto'
    colorthemeswitcher: 'true'
    enablesummary: true
    enablereadmorebutton: true
    paginationsinglepost: true
    tocsthreshold: 300
    social:
      - id: 'github'
        url: 'https://github.com/itsallcode'
      - id: youtube
        url: 'https://www.youtube.com/@itsallcode-org'

menu:
  main:
    - identifier: 'home'
      name: 'Home'
      url: '/'
      weight: 1

    - identifier: 'oft'
      name: 'OpenFastTrace'
      url: 'https://github.com/itsallcode/openfasttrace'
      weight: 10

    - identifier: 'wr'
      name: 'White Rabbit'
      url: 'https://github.com/itsallcode/white-rabbit'
      weight: 20

    - identifier: 'tags'
      name: 'Tags'
      url: '/tags/'
      weight: 30

    - identifier: 'archive'
      name: 'Archive'
      url: '/posts/'
      weight: 40

    - identifier: 'about'
      name: 'About'
      url: '/pages/about'